export const NOTIFICATION_TYPES = [
    "ANNOUNCEMENT",
    "PROJECT_APPROVAL_STATUS:SUBMITTED",
    "PROJECT_APPROVAL_STATUS:VERIFIED",
    "PROJECT_APPROVAL_STATUS:APPROVED",
    "PROJECT_APPROVAL_STATUS:EVALUATED",
    "PROJECT_NOTICE",
  ];