export const DATA_ENTRY_ROLES = ["DATA_PREPARE","DATA_SUBMIT"];


export const PROJECT_ASSIGNED_TO_DATA_APPROVE = ["SUBMITTED"]
export const PROJECT_ASSIGNED_TO_DATA_SUBMIT = ["APPROVAL_REJECTED","PREPARED"]