export const DATA_ENTRY_ROLES = ["DATA_PREPARE", "DATA_SUBMIT", "SUPER_ADMIN"];
export const DATA_REJECT_ROLES = ["DATA_APPROVE", "DATA_SUBMIT", "SUPER_ADMIN"];
export const DATA_DRAFT_ROLES = ["DATA_PREPARE", "SUPER_ADMIN"];

export const PROJECT_ASSIGNED_TO_DATA_APPROVE = ["SUBMITTED"];
export const PROJECT_ASSIGNED_TO_DATA_SUBMIT = [
  "APPROVAL_REJECTED",
  "PREPARED",
];
