export const DATA_ENTRY_ROLES = ["PREPARER", "SUPER_ADMIN"];
export const DATA_REJECT_ROLES = ["EVALUATOR", "VERIFIER", "SUPER_ADMIN"];
export const DATA_DRAFT_ROLES = ["PREPARER", "SUPER_ADMIN"];
export const DATA_APPROVE_ROLES = ["EVALUATOR", "SUPER_ADMIN"];

export const PROJECT_ASSIGNED_TO_DATA_APPROVE = ["SUBMITTED"];
export const PROJECT_ASSIGNED_TO_DATA_SUBMIT = [
  "APPROVAL_REJECTED",
  "PREPARED",
];

export const ALL_USER_ROLES = [
  "PREPARER",
  "VERIFIER",
  "APPROVER",
  "EVALUATOR",
  "ADMIN",
  "SUPER_ADMIN",
];


export const ALL_ADMINS = ["ADMIN", "SUPER_ADMIN"];
export const USER_JURISDICTIONS = [
  "WARD",
  "DEPARTMENT",
  "PALIKA",
  "PROVINCE",
  "COUNTRY",
];
export const USER_ROLES_WITH_PALIKA_JURISDICTION = ["ADMIN", "EVALUATOR"];